version: '3'

volumes:
  pg_data_production:
  static:

services:
  db:
    image: postgres:13.0-alpine
    env_file: ../.env.db
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: chemisto/street_russia_backend:latest
    env_file: ../.env
    volumes:
      - static:/app/static
    depends_on:
      - db
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"

  gateway:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/app/static
    ports:
      - "80:80"
    depends_on:
      - backend
